[package]
name = "glsl-std140"
version = "0.1.0"
authors = ["Zakarum <scareaangel@gmail.com>"]
description = "Provides data types from glsl with matching alignment requirements."


[features]
bigger-arrays = []


[dependencies]
cgmath = { version = "0.16", optional = true }