[package]
name = "glsl-layout-std140"
version = "0.1.0"
authors = ["Zakarum <scareaangel@gmail.com>"]
description = "Provides data types from glsl with matching alignment requirements."
license = "MIT/Apache-2.0"
repository = "https://github.com/omni-viral/glsl-layout-std140"

[features]
bigger-arrays = []

[dependencies]
cgmath = { version = "0.16", optional = true }
