[package]
name = "glsl-layout-derive"
version = "0.1.0"
authors = ["Zakarum <scareaangel@gmail.com>"]

[lib]
proc-macro = true

[features]
gfx = []

[dependencies]
syn = { version = "0.13", features = ["full"] }
quote = "0.5"
